server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://NOYSS: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@github.com/NOYSS/spring-cloud-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
